### ISSUE TITLE
Server Villager trading

### ISSUE THREAD

**Issue by GooseCarnival** [LiviiYS/Euphoric_Curiosity#12]
Title. Villager trades aren't working. No lag or crash associated, just no reaction when right clicking. Tried on several races and classes.

**Comment by GooseCarnival** [comment]
After removing and starting up many many times, i found out requiem is the culprit. I can speak to villagers after removing it

**Comment by NetIsPrograming** [comment]
I can confirm the villagers don't seem to work.
