### ISSUE TITLE
Tinkerer Bug:  Can't build Elytra

### ISSUE THREAD

**Issue by Sajier** [LiviiYS/Euphoric_Curiosity#15]
Tried to craft Elytra (2 popped chorus fruit, 5 phantom membrane https://imgur.com/Ln24fkr) and it doesn't work.  Have succeeded with other recipes (enchanted apple, totem of everliving) with no issues.

**Comment by Sound311** [comment]
If you join the world its saying some recipes have been removed for balance. Cant craft if either.

**Comment by LiviiYS** [comment]
Is this from 1.17 or 1.18, need to know so I can fix.

**Comment by Sajier** [comment]
This was on 1.18.1 (v0.4).

**Comment by LiviiYS** [comment]
Please update to 0.5
