### ISSUE TITLE
Put in spectator mode after death

### ISSUE THREAD

**Issue by DistantDig** [LiviiYS/Euphoric_Curiosity#19]
I’m a mortal, and hexblade. Whenever I’m killed I’m  put into spectator mode shortly after respawning. I’m positive I’m not in the ghost form from requiem

**Comment by DistantDig** [comment]
To add to this, whenever I use the hexblade’s phasing ability, I suffocate in the walls. This is not the case on single player

**Comment by LiviiYS** [comment]
Fixed in 0.5B
