### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by Sajier** [LiviiYS/Euphoric_Curiosity#23]
GrimTech and I were trying to find where we were going to set up and both started crashing to desktop.

Here is the crash report:
Sajier:
https://paste.gg/p/anonymous/a1410d15ff5041a1aed108c268c0a010

Grim:
https://paste.gg/p/anonymous/dc34ceaa501b44a99e81005a84ac5a46

**Comment by LiviiYS** [comment]
Should be fixed in 0.7
