### ISSUE TITLE
Broken furnace recipe: cobblestone to stone. 

### ISSUE THREAD

**Issue by tevaearai** [LiviiYS/Euphoric_Curiosity#24]
Trying to smelt cobblestone to make stone wont work, looks like the recipe is missing. Tried different furnaces on different spots, and different fuel sources.

When opening the Green Recipes Book will show a recipe to make air, and will place cobble on the furnace on clicking. Also, JEI shows cobble's smelting recipe to an empty output.

Looks like the recipe itself is broken, because I can smelt other stuff.

![image](https://user-images.githubusercontent.com/83216575/147702538-7b92d6a0-bade-42e6-95c8-cc62d1ba2b84.png)

![image](https://user-images.githubusercontent.com/83216575/147702529-c1313ce6-7cb6-4dc4-929c-17d6fa693a74.png)

![image](https://user-images.githubusercontent.com/83216575/147702646-b2381e1b-0b45-4df5-b517-22c52680809d.png)

![image](https://user-images.githubusercontent.com/83216575/147702808-18fc475b-c53a-47ae-bec9-44a81102d60c.png)

**Comment by LiviiYS** [comment]
Fixed in 0.7
