### ISSUE TITLE
Version 0.7 will not boot up

### ISSUE THREAD

**Issue by AndyTran11** [LiviiYS/Euphoric_Curiosity#29]
![RuntimeError](https://user-images.githubusercontent.com/95604037/147892375-d8681c04-a7a3-4a31-be45-9aeb3914aebf.PNG)

Here's the log:
https://gist.github.com/AndyTran11/146e407baaa376dff0aab997cb5980cf

**Comment by Sound311** [comment]
Try to use java 17
