### ISSUE TITLE
Getting a Crash On Startup That Points To This Mod

### ISSUE THREAD

**Issue by Bubbadoo** [LiviiYS/Euphoric_Curiosity#43]
Currently using a modified version of the Curious Fox Modpack that did come with this mod inherently, only adding like.. ~15 or so extra mods to it, (And removing some small mods like the first person models, that mod drives me nuts) and clicking update on all mods that said they had old versions in the pack too. So possibility this is a mod not playing nice with this one? The strangest thing is however is that the first time this happened the first bootup it boots up fine, but the second and following times I boot it up it has this issue until I reinstalled that mod. It let me do this fine say like 4 bootups where I had to reinstall and the mod then seemed to work fine and the game booted up, but I closed to install one more mod and now this crash is consistent no matter how many times I try to reinstall Bountiful.

Log provided here:
[crash-2022-01-12_01.41.45-client.txt](https://github.com/LiviiYS/Euphoric_Curiosity/files/7853005/crash-2022-01-12_01.41.45-client.txt)

I think this is the main take-away is this? "Caused by: java.lang.AbstractMethodError: Receiver class io.ejekta.bountiful.content.BountifulContent does not define or inherit an implementation of the resolved method 'abstract void beforeRegistration()' of interface io.ejekta.kambrik.registration.KambrikAutoRegistrar."

**Comment by LiviiYS** [comment]
That is the issue.

modified modpacks are not supported

**Comment by Bubbadoo** [comment]
So sorry! I don't know how I ended up posting this issue in a different modpack, I meant to post this in the mod page.. I somehow mixed up what github I was on.

**Comment by Bubbadoo** [comment]
Oh shit, I figured out why, my dumbass was looking at the issues I had posted earlier to see if I got a reply
And I accidentally posted this here instead of the bountiful issues page.

**Comment by Bubbadoo** [comment]
For the record, I managed to corrupt Kambrik I guess
It took a reinstall of both it and Bountiful and now that modpack is working fine.
