### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by MyNameScotland** [LiviiYS/Euphoric_Curiosity#45]
I recently tried setting up a Multicraft server running Euphoric Curiosity, after trying to join the server I get the error "Disconnected" on the Minecraft application and the error "io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null)" in the console of the server.
Not sure if this is an issue with improperly setting up a server or if it's a issue related to the pack itself, I have ran other packs on the server without issue but none of them were fabric. I have also combed through the mods list of both the server and the downloaded version hosted on curseforge, the modlists match up excluding 2, 1 being medieval music and the other being the folder, both of them are client side so I wouldn't expect that to be the primary issue. I hope this isn't too much cause for concern and I hope I can get help with resolving it. Any further error messages or information on the server I can gladly reply with.

**Comment by Slugstur1** [comment]
This has likely to do with a known issue. The pack has some custom settings for Spectrum which aren't working correctly, this is being investigated.

To get your server going you can either:
- Remove the custom config for Spectrum server side
- Remove the Spectrum mod server and client side
- Wait for a fix

**Comment by LiviiYS** [comment]
This has just been fixed on 1.0.1
