### ISSUE TITLE
Extreme lag happening (<1 FPS)

### ISSUE THREAD

**Issue by jezzen** [LiviiYS/Euphoric_Curiosity#50]
The game was doing fine for a while as I was doing some exploring then suddenly I got hit with just going 0-1 frames. Goes back to normal in the menu, and minimizing render distance only got to 1-2 frames.

F3 menu shows nearly 7K water ambient entities and reloading the world let me see tons of fish generating while the textures were still loading in.

![2022-01-24_16 44 38](https://user-images.githubusercontent.com/18730266/150736079-995075a9-ce06-40b9-90a8-ccedd91dbb7a.png)
![2022-01-24_16 54 04](https://user-images.githubusercontent.com/18730266/150736093-52015741-990e-4b53-b85d-a92076755117.png)
![2022-01-24_16 59 53](https://user-images.githubusercontent.com/18730266/150736336-d9fefd9e-03da-43f7-9c50-8a863e9e61dc.png)

I'm in a lush forest biome, incase that's doing something weird with whichever mod is spawning the fish.

**Comment by jezzen** [comment]
Just looked up the lush forest mod and it's already been updated to fix it. Please include that update soon

**Comment by Albertsmods** [comment]
While your waiting for the modpack to update you could manually update the mod.
