### ISSUE TITLE
Unable to join private multiplayer server

### ISSUE THREAD

**Issue by Estous** [LiviiYS/Euphoric_Curiosity#55]
![Capture](https://user-images.githubusercontent.com/98872832/152112304-878ac7b5-81fa-46b7-a6fd-81779febc751.PNG)
[2022-02-02-1.log.gz](https://github.com/LiviiYS/Euphoric_Curiosity/files/7984437/2022-02-02-1.log.gz)

**Comment by Nik-Kot** [comment]
Now exactly the same thing is happening to me when I try to join the official modpack server.
