### ISSUE TITLE
Modpack needs ore dictionary or similar

### ISSUE THREAD

**Issue by marybrook** [LiviiYS/Euphoric_Curiosity#65]
The recipes for rock salt and ore from modern industrialization cant be smelted/crafted into anything. 
![image](https://user-images.githubusercontent.com/101207311/157291982-76871012-ac28-4bbd-a571-58b0ea2dd925.png)
![image](https://user-images.githubusercontent.com/101207311/157292092-3d51e2a4-a30a-4124-ba3a-568fb663cd9e.png)
![image](https://user-images.githubusercontent.com/101207311/157292140-8aea4329-b064-4c00-95c6-925fc2ef9c66.png)
and others
is there a way to maybe remove it completely from the game or smelt them into ore from techreborn?

**Comment by LiviiYS** [comment]
Should be fixed in latest test thats on the discord server.
