### ISSUE TITLE
[owo] Handshake failure - cant connect to server

### ISSUE THREAD

**Issue by Def-Not-Ryan** [LiviiYS/Euphoric_Curiosity#72]
![image](https://user-images.githubusercontent.com/102449906/160264454-55a97cde-6843-41e6-8753-217a3f8e9efb.png)

I've been trying to connect to a server I have set up on my other computer, and have also tried connecting to the general server and keep getting the same error

I can't find anything online either so idk how to fix it 

any ideas on how to fix it?

**Comment by LiviiYS** [comment]
Need logs

**Comment by philip1337** [comment]
I got the same:
![image](https://user-images.githubusercontent.com/5432423/162581184-f8c9285f-980b-482b-a4d7-b04c3f4bedc0.png)

mc_1  | [15:40:51] [Server thread/INFO]: Reloaded configs for mousewheelie (server/world)
mc_1  | [15:40:54] [Server thread/WARN]: @Redirect conflict. Skipping lithium.mixins.json:alloc.entity_tracker.EntityTrackerMixin->@Redirect::useFasterCollection()Ljava/util/Set; from mod lithium with priority 1000, already redirected by krypton.mixins.json:shared.network.microopt.TacsTrackedEntityMixin->@Redirect::construct$useFastutil()Ljava/util/Set; from mod krypton with priority 1000
mc_1  | [15:40:58] [C2ME worker #1/INFO]: [STDOUT]: Stronghold positions initialized
mc_1  | [15:41:56] [User Authenticator #1/INFO]: UUID of player xxxxx is a1bf0ecd-b680-4c7a-8478-3e9d53e5882c
mc_1  | [15:41:56] [Server thread/INFO]: [Handshake] Sending channel query
mc_1  | [15:41:56] [Netty Epoll Server IO #4/INFO]: [Handshake] Receiving client channels
mc_1  | [15:41:56] [Netty Epoll Server IO #4/INFO]: Disconnecting com.mojang.authlib.GameProfile@5bffe55a[id=a1bf0ecd-b680-4c7a-8478-3e9d53e5882c,name=xxxxx,properties={textures=[com.mojang.authlib.properties.Property@4d6d1e01]},legacy=false] (/xxxxx:1376): [oωo] §chandshake failure
mc_1  | server is missing controllers:
mc_1  | §7mythicmetals:particles§r
mc_1  |
mc_1  | [15:41:56] [Server thread/INFO]: com.mojang.authlib.GameProfile@5bffe55a[id=a1bf0ecd-b680-4c7a-8478-3e9d53e5882c,name=xxxxx,properties={textures=[com.mojang.authlib.properties.Property@4d6d1e01]},legacy=false] (/xxxxx:1376) lost connection: [oωo] §chandshake failure
mc_1  | server is missing controllers:
mc_1  | §7mythicmetals:particles§r



We have several errors:

> mc_1  | [15:40:34] [Worker-Main-7/INFO]: Found 17024 recipes and 0 failed recipes in 371.8 ms
mc_1  | [15:40:35] [Worker-Main-7/INFO]: Posted recipe events in 765.9 ms
mc_1  | [15:40:35] [Worker-Main-7/WARN]: Error parsing recipe croptopia:shaped_fruit_cake[minecraft:crafting_shaped]: {"type":"minecraft:crafting_shaped","pattern":["61 ","324","857"],"key":{"1":{"item":"minecraft:air"},"2":{"item":"minecraft:sugar"},"3":{"tag":"c:fruits/lemons"},"4":{"tag":"c:nuts/pecans"},"5":{"item":"croptopia:cinnamon"},"6":{"item":"bewitchment:salt"},"7":{"tag":"c:crops/nutmeg"},"8":{"item":"minecraft:egg"}},"result":{"item":"croptopia:fruit_cake","count":3}}: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air
mc_1  | [15:40:35] [Worker-Main-7/WARN]: Error parsing recipe croptopia:shaped_scones[minecraft:crafting_shaped]: {"type":"minecraft:crafting_shaped","pattern":["567","234"," 1 "],"key":{"1":{"item":"croptopia:frying_pan"},"2":{"tag":"c:flour"},"3":{"item":"bewitchment:salt"},"4":{"item":"minecraft:sugar"},"5":{"item":"minecraft:egg"},"6":{"tag":"c:crops/vanilla"},"7":{"item":"minecraft:air"}},"result":{"item":"croptopia:scones","count":2}}: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air
mc_1  | [15:40:35] [Worker-Main-7/INFO]: [STDOUT]: empty indrev:salt
mc_1  | [15:40:35] [Worker-Main-7/WARN]: Error parsing recipe croptopia:fruit_smoothie[minecraft:crafting_shapeless]: {"type":"minecraft:crafting_shapeless","ingredients":[{"item":"minecraft:glass_bottle"},{"item":"minecraft:air"},{"item":"minecraft:air"},{"item":"minecraft:air"},{"item":"minecraft:ice"},{"tag":"c:milks"}],"result":{"item":"croptopia:fruit_smoothie","count":2}}: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air
mc_1  | [15:40:35] [Worker-Main-7/WARN]: Error parsing recipe valley:fruit_bowl[minecraft:crafting_shapeless]: {"type":"minecraft:crafting_shapeless","ingredients":[{"item":"minecraft:air"},{"item":"minecraft:air"},{"item":"minecraft:air"},{"item":"minecraft:air"},{"item":"minecraft:air"},{"item":"minecraft:air"},{"item":"minecraft:bowl"}],"result":{"item":"valley:fruit_bowl","count":1}}: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air
mc_1  | [15:40:35] [Worker-Main-7/WARN]: Error parsing recipe promenade:crafting/blue_dye_from_blueberries[minecraft:crafting_shapeless]: {"type":"minecraft:crafting_shapeless","group":"blue_dye","ingredients":[{"item":"minecraft:air"}],"result":{"item":"minecraft:blue_dye"}}: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air
mc_1  | [15:40:35] [Worker-Main-7/WARN]: Error parsing recipe croptopia:blueberry_jam[minecraft:crafting_shapeless]: {"type":"minecraft:crafting_shapeless","ingredients":[{"item":"minecraft:air"},{"item":"croptopia:cooking_pot"},{"item":"minecraft:sugar"}],"result":{"item":"croptopia:blueberry_jam","count":1}}: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air
mc_1  | [15:40:35] [Worker-Main-7/WARN]: Error parsing recipe bewitchment:silver_block[minecraft:crafting_shaped]: {"type":"minecraft:crafting_shaped","pattern":["###","###","###"],"key":{"#":{"item":"techreborn:silver_ingot"}},"result":{"item":"minecraft:air","count":1}}: com.google.gson.JsonSyntaxException: Invalid item: minecraft:air
mc_1  | [15:40:35] [Worker-Main-7/INFO]: Modified & removed recipes in 118.0 ms
mc_1  | [15:40:35] [Worker-Main-7/WARN]: Error creating recipe indrev:kjs_7wj8k670qp8s67dv56df7ovpe[indrev:compress]: {"type":"indrev:compress","ingredients":{"item":"techreborn:copper_ingot"},"output":{"item":"techreborn:copper_plate","count":1},"processTime":400}: com.google.gson.JsonSyntaxException: Unknown item 'techreborn:copper_ingot'
mc_1  | [15:40:35] [Worker-Main-7/WARN]: Error creating recipe indrev:kjs_6xwx6cqluvq2l9dz44fngii8o[indrev:compress]: {"type":"indrev:compress","ingredients":{"item":"techreborn:gold_ingot"},"output":{"item":"techreborn:gold_plate","count":1},"processTime":400}: com.google.gson.JsonSyntaxException: Unknown item 'techreborn:gold_ingot'
mc_1  | [15:40:35] [Worker-Main-7/WARN]: Error creating recipe indrev:kjs_drthqj399f15j6hnltawcoqou[indrev:compress]: {"type":"indrev:compress","ingredients":{"item":"techreborn:iron_ingot"},"output":{"item":"techreborn:iron_plate","count":1},"processTime":400}: com.google.gson.JsonSyntaxException: Unknown item 'techreborn:iron_ingot'
mc_1  | [15:40:35] [Worker-Main-7/INFO]: Added recipes in 7.269 ms
mc_1  | [15:40:35] [Worker-Main-7/INFO]: Added 79 recipes, removed 197 recipes, modified 2130 recipes, with 10 failed recipes and 0 fall-backed recipes
mc_1  | [15:40:35] [Worker-Main-7/ERROR]: Couldn't parse loot table croparia:blocks/block_crop_pear
mc_1  | java.lang.IllegalArgumentException: Can't find block croparia:block_crop_pear
mc_1  |         at net.minecraft.class_212$class_214.method_17937(class_212.java:79) ~[server-intermediary.jar:?]
mc_1  |         at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
mc_1  |         at net.minecraft.class_212$class_214.method_910(class_212.java:79) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_212$class_214.method_517(class_212.java:68) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
mc_1  |         at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
mc_1  |         at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_3518.method_15283(class_3518.java:466) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_79$class_5337.method_29319(class_79.java:85) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
mc_1  |         at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
mc_1  |         at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_3518.method_15272(class_3518.java:456) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_69$1.method_29313(class_69.java:61) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_69$1.method_424(class_69.java:53) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
mc_1  |         at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
mc_1  |         at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_3518.method_15272(class_3518.java:456) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[server-intermediary.jar:?]
mc_1  |         at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.8.jar:?]
mc_1  |         at net.minecraft.class_3518.method_15291(class_3518.java:448) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_3518.method_15283(class_3518.java:466) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_52$class_54.method_340(class_52.java:213) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_52$class_54.deserialize(class_52.java:209) ~[server-intermediary.jar:?]
mc_1  |         at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:1003) ~[gson-2.8.8.jar:?]
mc_1  |         at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.8.jar:?]
mc_1  |         at net.minecraft.class_60.method_20711(class_60.java:44) ~[server-intermediary.jar:?]
mc_1  |         at dev.latvian.mods.kubejs.core.LootTablesKJS.applyKJS0(LootTablesKJS.java:38) ~[kubejs-fabric-1801.4.3-build.307.jar:?]
mc_1  |         at net.minecraft.class_60.redirect$cpd000$applyKJS(class_60.java:2521) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_60.method_20712(class_60.java:42) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_60.method_18788(class_60.java:17) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
mc_1  |         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
mc_1  |         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
mc_1  |         at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
mc_1  |         at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
mc_1  |         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
mc_1  |         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
mc_1  |         at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
mc_1  |         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
mc_1  |         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
mc_1  |         at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
mc_1  |         at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
mc_1  |         at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
mc_1  |         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
mc_1  |         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
mc_1  |         at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
mc_1  |         at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
mc_1  |         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
mc_1  |         at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
mc_1  |         at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
mc_1  |         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
mc_1  |         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by Noaaan** [comment]
This handshake error likely means you have differing versions of Mythic Metals between your server and client. I dont know if it is still relevant though

**Comment by Coinzs** [comment]
So how would you fix that?
