### ISSUE TITLE
Can't produce tin Ingots

### ISSUE THREAD

**Issue by FBlumes** [LiviiYS/Euphoric_Curiosity#8]
I need Tin for Bronze, but there's no avaible recipe to smelt raw tin to Tin ingots, just with a machine, which needs tin to be built

**Comment by LiviiYS** [comment]
there is 3 different variants of tin, not all can be smelted.

let me know what type you are trying to use.

**Comment by LiviiYS** [comment]
also, to get bronze you need to use the alloy forge

**Comment by FBlumes** [comment]
i got the alloy forge, but then i got the "mythic" Bronze, i couldn't use it for any recipe

**Comment by LiviiYS** [comment]
Fixed in latest
