### ISSUE TITLE
Unable to enter /gamemode on Bisect server

### ISSUE THREAD

**Issue by Sammieborkbork** [LiviiYS/Euphoric_Curiosity#80]
I own a Bisect server and wanted to give this mod pack a try but I need to access my gamemode commands being server owner. Any and all attempts have failed, I've asked Bisect and everything is good on their end. I've reinstalled, refreshed and searched across google. 

It seems the gamemode command and anythign similar cannot be found within the server itself.

Please and thank you for the help.

**Comment by LiviiYS** [comment]
You just need to don/gamemode in the server panel with the user you want
