### ISSUE TITLE
Farmer's Delight Pantry

### ISSUE THREAD

**Issue by Jaloyoloti** [LiviiYS/Euphoric_Curiosity#85]
Put down a Farmer's delight pantry on a server, crashed and now crashes every time I try to log onto the server.
Thanks in advance for your help!
Let me know if there's anything else you need.

[Crash Log](https://gist.github.com/Jaloyoloti/c7a30369d58baa2f72d681ce15553dcc)

**Comment by Crendgrim** [comment]
Greetings! I just stumbled across this issue.

It can be fixed by updating either DynamicCrosshair to 3.5.1, or Farmer's Delight to 1.3.1, or both.

ETA: I did add support for Farmer's Delight 1.3.1 to DynamicCrosshairCompat 1.4 if you would like improved crosshair support.
